Update fetch.yml

diff --git a/.github/workflows/fetch.yml b/.github/workflows/fetch.yml
--- a/.github/workflows/fetch.yml
+++ b/.github/workflows/fetch.yml
@@ -1,5 +1,3 @@
-# This is a basic workflow to help you get started with Actions
-
 name: Fetch data
 
 # Controls when the workflow will run
@@ -22,15 +20,30 @@ jobs:
       - uses: actions/checkout@v2
       
       - name: Download playlist.m3u file
-        run: curl "http://m3u4u.com/m3u/p87vnr5wegu44qe8y41j" -o playlist.m3u
-
-      # - name: Download EPG-Guide.xml.gz file
-      #  run: curl "http://m3u4u.com/epg/p87vnr5wegu44qe8y41j" -o EPG-Guide.xml.gz
-        
-      - name: Commit changes
+        id: download_playlist
         run: |
-         git config --local user.email "action@github.com"
-         git config --local user.name "GitHub Action"
-         git add .
-         git diff-index --quiet HEAD || git commit -m "actions-user: Fetch data workflow" -a
-         git push -f origin main:main
+          # Download the file and check the HTTP response code
+          http_code=$(curl -s -w "%{http_code}" -o playlist.m3u "http://m3u4u.com/m3u/p87vnr5wegu44qe8y41j")
+          if [[ "$http_code" != "200" ]]; then
+            echo "Download failed with HTTP code $http_code"
+            exit 1
+          fi
+          
+          # Check if the file size is greater than 0 bytes
+          file_size=$(stat -c%s "playlist.m3u")
+          if [[ "$file_size" -le 0 ]]; then
+            echo "File size is too small: $file_size bytes"
+            exit 1
+          fi
+        
+      # - name: Download EPG-Guide.xml.gz file
+      #   run: curl "http://m3u4u.com/epg/p87vnr5wegu44qe8y41j" -o EPG-Guide.xml.gz
+      
+      - name: Commit changes if playlist.m3u is updated
+        run: |
+          git config --local user.email "action@github.com"
+          git config --local user.name "GitHub Action"
+          git add playlist.m3u
+          git diff-index --quiet HEAD || git commit -m "actions-user: Fetch data workflow" -a
+          git push -f origin main:main
+        if: success()
